# Generated by Django 4.1.2 on 2022-10-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matricula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('status', models.IntegerField(default=0)),
                ('n_sancion', models.IntegerField(default=0)),
                ('duracion_sancion', models.DateTimeField(null=True)),
            ],
        ),
    ]
