# Generated by Django 4.1.2 on 2022-10-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='n_sancion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
