# Generated by Django 4.1.2 on 2022-10-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docentes_n_sancion_alter_docentes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='duracion_sancion',
            field=models.DateTimeField(null=True, verbose_name='Duración de sancion'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='n_sancion',
            field=models.IntegerField(default=0, null=True, verbose_name='Numero de Sanciones'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='status'),
        ),
    ]
