# Generated by Django 4.1.2 on 2022-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_alter_docentes_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='n_sancion',
            field=models.IntegerField(default='0', null=True, verbose_name='Numero de Sanciones'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='status',
            field=models.IntegerField(default='0', null=True, verbose_name='status'),
        ),
    ]
