# Generated by Django 4.1.2 on 2022-10-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_equipos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipos',
        ),
    ]
