# Generated by Django 4.1.2 on 2022-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matricula')),
                ('equipo_id', models.IntegerField(default='0', null=True, verbose_name='Equipo')),
                ('fecha_prestamo', models.DateTimeField(null=True, verbose_name='Fecha Prestamo')),
                ('status', models.IntegerField(default='0', null=True, verbose_name='status')),
                ('oportunidad', models.IntegerField(default='0', null=True, verbose_name='oportunidad')),
                ('fecha_entrega', models.DateTimeField(null=True, verbose_name='Fecha Entrega')),
            ],
        ),
    ]
