# Generated by Django 4.1.2 on 2022-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'HDMI'), (2, 'LAPTOP')], verbose_name='Categoria'),
        ),
    ]
