# Generated by Django 4.1.2 on 2022-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='categoria',
            field=models.IntegerField(default='0', verbose_name='Categoria'),
        ),
    ]
